# Generated by Django 5.2 on 2025-05-25 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_remove_post_excerpt_post_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="description",
            field=models.TextField(max_length=255),
        ),
    ]
