# Generated by Django 5.2 on 2025-05-25 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_post_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="viewcount",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="blogpost_view_count",
                to="blog.post",
            ),
        ),
    ]
